config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers, :breweries

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_ban', on: :member
  end

  resources :memberships do
    post 'confirm', on: :member
  end

  root 'breweries#index'

  resources :ratings, only: [:index, :new, :create, :destroy]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resource :session, only: [:new, :create, :destroy]

  resources :places, only: [:index, :show]
  post 'places', to:'places#search'

  get 'beerlist', to:'beers#list'
  get 'brewerieslist', to:'breweries#list'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base
  has_many :memberships, -> { where confirmed:true }, dependent: :destroy
  has_many :members, through: :memberships, source: :user

  has_many :applications, -> { where confirmed:[nil, false] }, dependent: :destroy, class_name: "Membership"
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_admin, only: :destroy
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)
    @membership = Membership.new
    @membership.beer_club = @beer_club
    @membership.confirmed = true

    respond_to do |format|
      if @beer_club.save && @membership.save
        current_user.memberships << @membership
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render :show, status: :created, location: @beer_club }
      else
        format.html { render :new }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer_club }
      else
        format.html { render :edit }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url, notice: 'Beer club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
    <%= f.label :founded %><br>
    <%= f.number_field :founded, class:"form-control" %>
    <%= f.label :city %><br>
    <%= f.text_field :city, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/beer_clubs/edit.html.erb
<h1>Editing Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_club, class:"btn btn-primary" %>
<%= link_to 'Back', beer_clubs_path, class:"btn btn-default" %>

app/views/beer_clubs/index.html.erb
<h1>Beer Clubs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Founded</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= link_to beer_club.name, beer_club %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to('New Beer club', new_beer_club_path, class:"btn btn-primary") if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New Beer Club</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_clubs_path, class:"btn btn-default" %>

app/views/beer_clubs/show.html.erb
<h1>
  <%= @beer_club.name %>
</h1>
<div class="col-sm-6">
<div class="panel panel-default">
  <div class="panel-body">
<h4>
<%= @beer_club.city %>
</h4>

<p>
  Founded in
  <%= @beer_club.founded %>
</p>
</div>
</div>
  <ul class="list-group">
    <li class="list-group-item list-group-item-title">Members</li>
    <% @beer_club.members.each do |member| %>
      <li class="list-group-item"><%= link_to member.username, member %>
    <% end %>
  </ul>

<% if @beer_club.members.include? current_user and !@beer_club.applications.empty? %>
  <ul class="list-group">
    <li class="list-group-item list-group-item-title">Applications</li>
  <% @beer_club.applications.each do |application| %>
    <li class="list-group-item"><%= link_to application.user.username, application.user %>
        <%= link_to "confirm", confirm_membership_path(application), method: :post, class:"badge" %>
    </li>
  <% end %>
  </ul>
  <% end %>

<% if current_user and !current_user.beer_clubs.include? @beer_club %>
  <%= form_for(@membership) do |f| %>
    <%= f.hidden_field :beer_club_id %>
    <%= f.submit value:"join the club", class:"btn btn-primary" %>
  <% end %>
<% elsif current_user.beer_clubs.include? @beer_club %>
  <%= form_for(@membership, method: "delete") do |f| %>
  <%= f.hidden_field :beer_club_id %>
    <%= f.submit value:"leave the club", class:"btn btn-danger" %>
  <% end %>
<% end %>
<br />

<%= link_to 'Edit', edit_beer_club_path(@beer_club), class:"btn btn-primary" %>
<%= link_to 'Back', beer_clubs_path, class:"btn btn-default" %>
</div>